[package]
name = "puddle"
version = "0.1.0"
edition = "2024"

[features]
default = ["hidapi"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bitflags = { version = "2" }
clap = { version = "4", features = ["derive"] }
hidapi = { version = "2", features = ["macos-shared-device"], optional = true }